[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-blog_os.json"

# `cargo run` will run with qemu
[target.'cfg(target_os = "none")']
runner = "bootimage runner"
